language: android
os: linux
dist: trusty
jdk: oraclejdk8
android:
  components:
  - build-tools-26.0.3
  - build-tools-27.0.3
  - build-tools-28.0.2
  - build-tools-28.0.3
  - build-tools-29.0.2
  - build-tools-29.0.3
  - build-tools-30.0.2
  - android-25
  - android-26
  - android-27
  - android-28
  - android-29
  - android-30
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "/usr/local/android-sdk*/"
before_install:
- if [ "$encrypted_3571c34b0299_key" != "" ] && [ "$encrypted_3571c34b0299_iv" != "" ]; then
  openssl aes-256-cbc -K $encrypted_3571c34b0299_key -iv $encrypted_3571c34b0299_iv -in .travis/secring.gpg.enc -out .travis/secring.gpg -d;
  fi
- if [ "$encrypted_d32d0189ba50_key" != "" ] && [ "$encrypted_d32d0189ba50_iv" != "" ]; then
  openssl aes-256-cbc -K $encrypted_d32d0189ba50_key -iv $encrypted_d32d0189ba50_iv -in .travis/gnirces.gpg.enc -out .travis/secring.gpg -d;
  fi
before_script:
- chmod +x gradlew
script:
- "./gradlew assemble -S --no-daemon"
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    tags: true
after_deploy:
- "./gradlew closeAndReleaseRepository --no-daemon"
- shred -u .travis/secring.gpg
